### ISSUE TITLE
Add some more resources

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/DES-Website#104]
https://www.freecodecamp.org/news/free-textbooks-math-science-and-more-online-pdf-for-college-and-high-school/

**Comment by acenasir** [comment]
https://www.classcentral.com/

**Comment by deejayjay** [comment]
[ComIT](https://www.comit.org)

**Comment by Rajiv-paul** [comment]
assign me with this issue

**Comment by sdhinsa11** [comment]
I would like this issue

**Comment by MandyMeindersma** [comment]
ComIT has been added but the others are still needed :)
