### ISSUE TITLE
Update Nuxt to v3

### ISSUE THREAD

**Issue by blerg-rush** [devedmonton/DES-Website#124]
Nuxt 3 (which uses Vue 3) is [now in beta](https://nuxtjs.org/announcements/nuxt3-beta/). As soon as it's production-ready (once there's a release candidate build), we should look into upgrading!

**Comment by dboydgit** [comment]
Semi related, we have a few warnings from npm in our packages.

I tried running some updates locally to fix (not nuxt v3) and failed miserably 😬  things are a little more difficult with tailwind being involved.

**Comment by MandyMeindersma** [comment]
@blerg-rush I remember saying you really wanted to do this one, is that still the case lol?

**Comment by olimpiuus** [comment]
> @blerg-rush I remember saying you really wanted to do this one, is that still the case lol?

I played some time with it. And we need also to migrate to vue 3 at the same time.

https://nuxt.com/docs/migration/overview

**Comment by deejayjay** [comment]
@MandyMeindersma: Isn't this upgrade completed successfully? Shall we close this issue?

**Comment by MandyMeindersma** [comment]
woops yup! Forgot to close
