### ISSUE TITLE
Add a section linking to other useful Slacks

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/DES-Website#126]
We're part of the community and there are lots of other good Slacks out there. Some off the top of my head...

* Product Edmonton
* Startup Edmonton
* YYCDesign
* Digital Edmonton (UX/IA) --> https://join.slack.com/t/digitaledmonton/shared_invite/zt-7ka8gm45-cVNFyy1wp9R0wunz46vrlQ
* YEG DEV

Lots more! :)

**Comment by MandyMeindersma** [comment]
There is a pinned message in the #events channel on slack that lists a whole bunch of discords too

**Comment by MandyMeindersma** [comment]
I think we would have to create some other section on our site to fit this in, cause the homepage is starting to get a bit big, or maybe these won't be cards? Not sure

**Comment by MandyMeindersma** [comment]
There are a ton listed in this mail chimp email I sent out too

https://mailchi.mp/43291c8eceb8/rsvp-for-our-picnic-next-weekend

**Comment by MandyMeindersma** [comment]
This is the yeg dev link: https://yegdev.slack.com/

**Comment by dgmouris** [comment]
Hey @MandyMeindersma is this still something is wanted on the site.

I might have a few people who are interested in doing this.

As well I think it would be awesome to have a centralized place for all of the other meetups such as:

AMII: https://www.amii.ca/events/ 
Google Developer Group Edmonton - https://www.meetup.com/gdg-cloud-edmonton/ 
Demo Camp - https://www.eventbrite.ca/o/democamp-edmonton-56126644423 
Edmonton R User Group - [https://](https://www.meetup.com/edmonton-r-user-group-yegrug/)[DeDemoCamp Edmonton Events | EventbritemoCamp Edmonton Events | Eventbrite](https://www.eventbrite.ca/o/democamp-edmonton-56126644423)[ww.meetup.com/edmonton-r-user-group-yegrug/](https://www.meetup.com/edmonton-r-user-group-yegrug/)
Hacked (https://hacked.compeclub.com/)

Let me know what you think

**Comment by MandyMeindersma** [comment]
@dgmouris yes would absolutely love that!

So some of these we already have but it isn't organized very well (if someone like you in the community can't easily find them) So would be happy for suggestions to rearrange them

- AMII: https://www.amii.ca/events/
    - on our resources tab https://devedmonton.com/resources (let me know if it should be somewhere more helpful)
- Google Developer Group Edmonton - https://www.meetup.com/gdg-cloud-edmonton/
    -  on our events tab https://devedmonton.com/events  (let me know if it should be somewhere more helpful)
- Demo Camp - https://www.eventbrite.ca/o/democamp-edmonton-56126644423
    - This one does need to be added somewhere 
- Edmonton R User Group - [https://](https://www.meetup.com/edmonton-r-user-group-yegrug/)
    - on meetup tab https://devedmonton.com/meetups (let me know if it should be somewhere more helpful)
- Hacked (https://hacked.compeclub.com/)
    - this one needs to be added too!

**Comment by dgmouris** [comment]
Hey @MandyMeindersma, 

Thanks for the response :) (I hope you're doing well)

The existing ones are great and organized.

I think just adding:
- [DemoCamp](https://www.eventbrite.ca/o/democamp-edmonton-56126644423) to meetups we support would make sense.
- [HackEd](https://hacked.compeclub.com/) to the meetups page would make sense.

There's two more hackathons that I think are happening that I'd like to have noted.
- NAIT is hosting one that is open to all high school students (I'll get that link shortly)
- There was the GovTech hackathon, I hope they're doing it again this year.

Besides that I think we can close this issue after adding this.

PS. I'm doing this trying to get some more students at NAIT to contribute to this repo so hopefully someone will make a PR for this :)

**Comment by MandyMeindersma** [comment]
Hacktoberfest is coming up :)

**Comment by Atremblay9** [comment]
Hey! I noticed that the link for Edmonton Data Science Community leads to a meetup that no longer exists. https://www.meetup.com/edmonton-data-science-community/

**Comment by dgmouris** [comment]
Hey @MandyMeindersma,

When working on this issue with students one thing that we came into is we want to add the logos for democamp yeg to https://ik.imagekit.io/des. I don't know how to do this, is this just open to you and some core contributors.

I think this would be an awesome opportunity to document :) 

Here's what I was thinking for link on democamp:
- https://ik.imagekit.io/des/meetups/DemoCamp.png

Here's the image from their website. https://profweb-live.s3.us-west-2.amazonaws.com/media/public/Screenshot_2024-05-15_at_3.26.21_PM.png

Here's the path that I was thinking for hacked.
- https://ik.imagekit.io/des/meetups/HackEd.png

Here's a link to the https://hacked.compeclub.com/static/media/HackedCircle.609e5186df6e9e190993.png

Let me know if I'm missing something or if you need more information on this @MandyMeindersma, thanks so much for your help.

**Comment by dgmouris** [comment]
I'm going to leave this PR in progress until we kind of figure the images, as well I'm doing this with students to try to help learn more about contribute. Essentially I'll only be working on this on fridays.

Thanks again!

**Comment by MandyMeindersma** [comment]
Woops yes I should have documented that. Anyone on the board can upload photos but if you want Dan I can give you the credentials too

It's kind of a pain but it is really performant so 🤷

**Comment by MandyMeindersma** [comment]
Uploaded now: 
https://ik.imagekit.io/des/events/hackEd.png
https://ik.imagekit.io/des/events/DemoCamp.png

I currently added them to events but I think I am going to make an issue to squish events and meetups anyways. Cause there is no real different between them

**Comment by MandyMeindersma** [comment]
https://github.com/devedmonton/DES-Website/pull/380

**Comment by dgmouris** [comment]
>Woops yes I should have documented that. Anyone on the board can upload photos but if you want Dan I can give you the credentials too

> It's kind of a pain but it is really performant so 🤷

Yes please send me the credentials maybe we should do that on slack or something rather than here:)

Thanks @MandyMeindersma :)

**Comment by MandyMeindersma** [comment]
Beautiful! So I'll close this issue cause this adds most of the other meetups but I will make a new issue to add more of those other slacks mark was talking about: https://github.com/devedmonton/DES-Website/issues/393
