### ISSUE TITLE
Should we set up an easy to remember redirect to the bylaws?

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/DES-Website#136]
We could add something like https://devedmonton.com/bylaws maybe?

**Comment by MandyMeindersma** [comment]
This would mean changing the footer and also the link added here (https://devedmonton.com/become_a_member) to point to the new link

**Comment by NonMint** [comment]
I think this is a good idea. We could link to them much easier in the DES meetings.

**Comment by MandyMeindersma** [comment]
absolutely! :)

**Comment by MandyMeindersma** [comment]
Now that our _redirects file is back in use this one should be a lot easier
