### ISSUE TITLE
Brand Assets

### ISSUE THREAD

**Issue by NonMint** [devedmonton/DES-Website#137]
We should generate a small collection of brand assets for DES stuff that we can store in our public google drive folder for when we want to be a little bit more official. We have a nice SVG logo, and should use that to come up with some super quick brand assets. I'm not the greatest at SVGing, but from what I've seen from social media assets, the following list should be good for 90% of our needs:

-     Instagram Ad: 1080 x (566 to 1350) 
-     Twitter Ad: 1200 x 675
-     LinkedIn or Facebook Ad: 1200 x 627
-     Vertical Call to Action: 200 x 600
-     Horizontal Call to Action: 600 x 200
-     Email Banner: 650 x 150

**Comment by celianux** [comment]
Happy to do this one!

**Comment by MarkBennett** [comment]
Did we ever get a license for Canva or Figma? Those seem like a great way to create and share these assets? Might be worth asking if anyone in the community has a lead on a not-for-profit license.

**Comment by acenasir** [comment]
@NonMint I would like to take this on board. Can you share the SVG. I can put all the Ad templates together and then upload them to the drive as needed :)

**Comment by MandyMeindersma** [comment]
All our logos and things are here: https://drive.google.com/drive/u/1/folders/1pv4ArA5WHm1F0TgttNnWKjbIJA5RhlRp

**Comment by acenasir** [comment]
Iv put some basic templates/brand assets together where can I share these? I would like an email address as its a canva folder I would like to share to..

**Comment by MandyMeindersma** [comment]
board@devedmonton.com

**Comment by MandyMeindersma** [comment]
Thank you!

**Comment by acenasir** [comment]
Invitation sent. Its just a start. Any feedback is welcome to adjust those templates but using the color of the logo is the color scheme I ended up using for them..

**Comment by celianux** [comment]
Actually, our email for Canva is canva@devedmonton.com...

**Comment by acenasir** [comment]
Invitation sent

**Comment by acenasir** [comment]
Reviewed all comments/feedback adjusted accordingly. They were purely templates and I provided everyone full edit abilities to them so you are most welcome to adjust and use as needed going fwd.

**Comment by MandyMeindersma** [comment]
I vote this is done! Sorry it took so long to close @acenasir 😂
