### ISSUE TITLE
Improve our lighthouse scores

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#139]
![image](https://user-images.githubusercontent.com/17459171/155380079-b07448dd-cd39-4055-9f0e-f81dfcaf60f9.png)

A lot of these are just adding alt text to our images.

**Comment by MandyMeindersma** [comment]
I fixed some with this pr: https://github.com/devedmonton/devedmonton.com/pull/142

still could use some improvements though

![image](https://user-images.githubusercontent.com/17459171/155393301-3fa20c9f-a6b0-4e31-85d4-a94a80311431.png)

**Comment by MarkBennett** [comment]
It's feeling snappy for me @MandyMeindersma 🚀
