### ISSUE TITLE
Add edmonton tech wednesdays to community events

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#182]
https://www.eventbrite.ca/e/edmonton-tech-wednesdays-tickets-662082084337?aff=oddtdtcreator

The person who does this ticket will have to google to find a logo and also create a description. 

For the description: do your best researching the group and try to come up with a couple sentences that describes them. Usually I copy and paste from their website about us section or similar

**Comment by deejayjay** [comment]
@MandyMeindersma: I was unable to find a logo for this event. I have requested the organizer of the event for a logo. Do you want me to push my changes with a placeholder logo in the meantime?

**Comment by MandyMeindersma** [comment]
Yeah push your changes without the logo, idk if they will get one! Thank you!
