### ISSUE TITLE
When I click on an item in the menu, the menu doesn't collapse

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#186]
So on tablet and mobile, if I open the menu (hamburger button) and then I click on a section, it brings me to the correct section but it doesn't close the menu

**Comment by olimpiuus** [comment]
we also need to close navigation menu on click outside menu. but it looks not simple in vue (What i found now, we can add custom dirictive or add some dependancies for vue/core to use "ref" on templates).  By vanila JS way easier.
