### ISSUE TITLE
Rename `MeetupCard` to something else

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#192]
`MeetupCard` originally only held our meet ups now they are holding data such as community events and resources. 

I don't like renaming it to `Card` because that seems to vague

I think `MeetupEventResourceCard` is probably too long lol

`ExternalPeopleCard`? `ExternalServiceCard`? `ExternalInformationCard`? `ExternalResourceCard`?

`ExternalInformationCard` is my fave so far, maybe shorten to `ExternalInfoCard`???

**Comment by deejayjay** [comment]
I like `ExternalInfoCard` better. Concise, but meaningful. @MandyMeindersma I am assigning this to myself since I am still working with this component. Will work on this issue once we close PR#189.
