### ISSUE TITLE
Make the heading size consistent in all the pages

### ISSUE THREAD

**Issue by deejayjay** [devedmonton/DES-Website#202]
The headings in different pages in the DES website are not consistent. Refer to the images below:
![Contact Us Page](https://github.com/devedmonton/DES-Website/assets/72120524/4206ff57-fb96-4e0d-b399-42865230b432)
![Community Events Page](https://github.com/devedmonton/DES-Website/assets/72120524/a1127a53-9fbc-491f-a47a-430a532d76b5)

Please update the headings in the following pages to look consistent to the ones in the home page:
- become_a_member
- board_recruiting
- board
- code_of_conduct
- contact
- sponsors

**Comment by PraveenShinde3** [comment]
Hi, 
I have completed the adjustments for consistent heading size across all pages. Ready to push changes to the repository

**Comment by COLONEL-HERE** [comment]
Hey!,
Done the required changes, all the pages are looking consisent now. Ready to Push changes to the repository.

**Comment by deejayjay** [comment]
@PraveenShinde3 & @COLONEL-HERE, thanks for working on this issue so quickly.
On a side note, if you decide to start working on any of the issues in the repository from now on, kindly make sure that you assign the issue to yourself. This is to be done so that others would not start working on the same issue (which happened in the case of this issue) and spend time on it.
In this case, I believe @PraveenShinde3 was the one who commented that he had completed all the required changes, and I am going to have him create a pull request if that is okay.
@PraveenShinde3, could you please create a Pull Request from your forked repository, and assign it to me for review? Thanks

**Comment by COLONEL-HERE** [comment]
Ok, I will surely do that from next time.
