### ISSUE TITLE
Reduce size of images for board page

### ISSUE THREAD

**Issue by olimpiuus** [devedmonton/DES-Website#207]
We have some oversized images in the project. We need to optimize them for web. It could be done by any web service.

salmaIbrahim.jpg and mandyMeindersma.jpg are located in /public/img/boardPictures/.

<img width="590" alt="Screenshot 2023-08-21 at 10 34 40 PM" src="https://github.com/devedmonton/DES-Website/assets/101880197/07b3242f-ccb8-423e-8abd-77f750e94056">

also  /public//img/homepage/get-involved-meetups.png looks same.

**Comment by DerrykBoyd** [comment]
@MandyMeindersma what do you think about signing DES up for a free [imagekit.io](https://imagekit.io/plans) account? 

We can then move the images out of the repository and can easily get resized and optimised images through a url or vue sdk. We use it at work and it's great.

**Comment by MandyMeindersma** [comment]
I like this idea. I feel like before I upload people faces to this site though I should make sure they aren't doing anything suspicious, like I should probably actually read their terms and conditions?

So I'll add it to my to do list lol

**Comment by DerrykBoyd** [comment]
> I like this idea. I feel like before I upload people faces to this site though I should make sure they aren't doing anything suspicious, like I should probably actually read their terms and conditions?
> 
> So I'll add it to my to do list lol

Ha sure thing, I figured since we already upload to GitHub it would be similar. I've already scanned it for work. This is probably the relevant excerpt from the privacy policy https://imagekit.io/privacy-policy-new/

```
To provide our services, we capture and store some information about you and users uploading materials to ImageKit:

IP Addresses
Request Headers
Data submitted to our API

This data listed above are stored on secure servers. We don’t use data from uploaded files for anything, except for:

Detecting MIME-types (file types)
Converting or modifying media i.e resizing, cropping etc.
Delivering files and their modified versions via CDN

To provide you with the Services, we may store, process, and transmit information around the world—including those outside your country. We have a team dedicated to keeping your information secure and testing for vulnerabilities.
```

**Comment by MandyMeindersma** [comment]
Oh that is perfect! Thank you 

Yeah I'll make us an account

**Comment by MTaimoor99** [comment]
I would like to have this issue assigned to me once DES gets an ImageKit account.

**Comment by MandyMeindersma** [comment]
Absolutely! As a heads up though I might have to wait until next week to do it cause I have organized three events in the next three days 😂

**Comment by MTaimoor99** [comment]
Oh, that's not a big deal. I will be looking at other issues in the meanwhile as well as learning the basics of Vue 😁

**Comment by MandyMeindersma** [comment]
https://ik.imagekit.io/des/jeremyNickurak.jpeg?updatedAt=1693956866834

**Comment by MandyMeindersma** [comment]
So like this @DerrykBoyd ?

The only think I dislike about this is that any image we want on the website, means that someone with the login has to add it. Which I am fine with doing. Just adds another step. I can also probably give the login to some other people too

**Comment by MandyMeindersma** [comment]
Also wait I changed the url https://ik.imagekit.io/des/BoardPictures/jeremyNickurak.jpeg?updatedAt=1693957174088

**Comment by MandyMeindersma** [comment]
oh hmmm also @DerrykBoyd what does your company do with svg's? We have so many of them and it feels weird to either:
1. store svgs in an image resizer tool
2. Store the svgs in the repo like we do now away from all the other images in the image resizer tool

**Comment by DerrykBoyd** [comment]
> oh hmmm also @DerrykBoyd what does your company do with svg's? We have so many of them and it feels weird to either:
> 1. store svgs in an image resizer tool
> 2. Store the svgs in the repo like we do now away from all the other images in the image resizer tool

We don't use imagekit for storage, we just use the transform API. It's pointed to images in one of our S3 buckets. But for simplicity probably best to just keep these images in imagekit since should just be free tier usage.

Our svgs are mixed between in repo and in S3, I think either is fine.

Yeah some people will need access to manage the images. That's pretty standard.

**Comment by MandyMeindersma** [comment]
Here is info on how to transform the images @MTaimoor99 

https://docs.imagekit.io/features/image-transformations

**Comment by MandyMeindersma** [comment]
board images:
https://ik.imagekit.io/des/BoardPictures/laurenBriske.jpg?updatedAt=1693957179707
https://ik.imagekit.io/des/BoardPictures/abramHindle.jpg?updatedAt=1693957178223
https://ik.imagekit.io/des/BoardPictures/justiceHemming.jpg?updatedAt=1693957176850
https://ik.imagekit.io/des/BoardPictures/celiaNicholls.jpg?updatedAt=1693957175419
https://ik.imagekit.io/des/BoardPictures/jeremyNickurak.jpeg?updatedAt=1693957174088
https://ik.imagekit.io/des/BoardPictures/mandyMeindersma.jpg?updatedAt=1693957172789
https://ik.imagekit.io/des/BoardPictures/salmaIbrahim.jpg?updatedAt=1693957171200

homepage:
https://ik.imagekit.io/des/homepage/get-involved-meetups.png?updatedAt=1694046782277
https://ik.imagekit.io/des/homepage/provide-a-platform.jpg?updatedAt=1694046782142
https://ik.imagekit.io/des/homepage/meetups-and-events.jpg?updatedAt=1694046782121
https://ik.imagekit.io/des/homepage/connect-community.jpg?updatedAt=1694046782110
https://ik.imagekit.io/des/homepage/get-involved-dev.jpg?updatedAt=1694046782109

404:
https://ik.imagekit.io/des/404/css-800.jpg?updatedAt=1694046887477
https://ik.imagekit.io/des/404/google-800.jpg?updatedAt=1694046887362
https://ik.imagekit.io/des/404/magnifying-glass-800.jpg?updatedAt=1694046887371

**Comment by MandyMeindersma** [comment]
meetups:
https://ik.imagekit.io/des/meetups/yegwit.png?updatedAt=1694047415152
https://ik.imagekit.io/des/meetups/ruby-240px.png?updatedAt=1694047415147
https://ik.imagekit.io/des/meetups/JavaScript-logo-240px.png?updatedAt=1694047415126
https://ik.imagekit.io/des/meetups/dotNet_logo.png?updatedAt=1694047415091

events:
https://ik.imagekit.io/des/events/gdgLogo.png?updatedAt=1694047593207
https://ik.imagekit.io/des/events/clc.png?updatedAt=1694047593210
https://ik.imagekit.io/des/events/ohm.png?updatedAt=1694047593198
https://ik.imagekit.io/des/events/yeg-tech-wed.png?updatedAt=1694047593181
https://ik.imagekit.io/des/events/elug.png?updatedAt=1694047593180
https://ik.imagekit.io/des/events/rac.png?updatedAt=1694047593168
https://ik.imagekit.io/des/events/bcyeg.png?updatedAt=1694047593129

resources:
https://ik.imagekit.io/des/StartUpTNTLogo.jpg?updatedAt=1694047699653
https://ik.imagekit.io/des/techAlberta.png?updatedAt=1694047699634
https://ik.imagekit.io/des/ERIN+Logo.jpeg?updatedAt=1694047699633
https://ik.imagekit.io/des/isaic-icon-logo.png?updatedAt=1694047699627
https://ik.imagekit.io/des/Startup-Edmonton-Logo-300x116.png?updatedAt=1694047699598

**Comment by MandyMeindersma** [comment]
okay that should be all of them 😂

**Comment by DerrykBoyd** [comment]
Also link to View SDK which might make things much simpler https://docs.imagekit.io/getting-started/quickstart-guides/vuejs

**Comment by DerrykBoyd** [comment]
There hadn't been any movement on this so I decided to do it tonight. Turns out imagekit ingegrates nicely with `NuxtImg` so that was a bonus. After setting that up it was relatively easy to switch the images over.

https://image.nuxt.com/providers/imagekit
