### ISSUE TITLE
Rearrenge logos 

### ISSUE THREAD

**Issue by olimpiuus** [devedmonton/DES-Website#208]
Inside public/img/logos we have a big mess 😢. 
Need to rearrange these logos into at least three folders: meetups, resources and events. Update paths in components/MeetupsSection.vue, store/events.js and store/resources.js. 
<img width="288" alt="Screenshot 2023-08-26 at 11 00 17 AM" src="https://github.com/devedmonton/DES-Website/assets/101880197/6f4830a8-b84a-46b3-a8bb-9b29f1ec17ab">

**Comment by innith** [comment]
I will work on this.
