### ISSUE TITLE
ExternalInfoCard title is cut on mobile

### ISSUE THREAD

**Issue by olimpiuus** [devedmonton/DES-Website#209]
At mobile screens, from 640px to 740px, we have an issue with cut titles of ExternalInfoCards in Community Events and Resources sections.

<img width="703" alt="Screenshot 2023-08-26 at 12 45 00 PM" src="https://github.com/devedmonton/DES-Website/assets/101880197/91fc77ca-6f3f-41d3-be39-174ced01630a">

<img width="654" alt="Screenshot 2023-08-26 at 12 49 21 PM" src="https://github.com/devedmonton/DES-Website/assets/101880197/877198d1-ded8-4dff-a3a2-a36220c59dd1">

**Comment by olimpiuus** [comment]
issue presents also in https://devedmonton.com/all_events and https://devedmonton.com/all_resources pages. 

<img width="659" alt="Screenshot 2023-08-26 at 1 01 53 PM" src="https://github.com/devedmonton/DES-Website/assets/101880197/ab3a3816-1350-4b46-9492-0fc43c2a858c">

**Comment by felipolis** [comment]
hey, I think I know how I can solve this. Could you assign me on this?

**Comment by MandyMeindersma** [comment]
Absolutely! Thanks

**Comment by felipolis** [comment]
@MandyMeindersma Just made the PR :D

**Comment by DerrykBoyd** [comment]
I saw there was a merged PR for this, but I'm still seeing some minor issues

<img width="322" alt="image" src="https://github.com/devedmonton/DES-Website/assets/24216368/3f58a727-f461-47bd-bf36-b0e29172b882">

I might have a look into this as well if that's ok

**Comment by DerrykBoyd** [comment]
I believe this is good now so closing.
