### ISSUE TITLE
no working slack invintation links 

### ISSUE THREAD

**Issue by olimpiuus** [devedmonton/DES-Website#210]
We have no working slack invitation links in the meetups section: YEGRB and Edmonton.Py.

**Comment by MandyMeindersma** [comment]
So the links usually go to their sites. They haven't updated their cites in a while. I asked the python meet up group if they were going to update theirs a while ago and they said they would but I know it's hard. 

The ruby, python and JS meet ups have been in search of help and organizers for a while. I still want to highlight them but not sure how to do that when they are in limbo like this?

Maybe at the hackathon in september we can find more organizers and things

**Comment by DerrykBoyd** [comment]
Proposal:

Make the link out optional

- If the group still has an active slack channel, display the card with the slack channel name and people can find the group on slack. 
- If the group has no website and no active slack channel, remove that card.

**Comment by MandyMeindersma** [comment]
hahaha I am so emotionally attached to those meet ups. 

If after the hackathon, no one offers to revive them then we delete them? I have hope!!

**Comment by MandyMeindersma** [comment]
hmmmm what if we have the python and ruby meet up point to the JS site for now?

**Comment by MandyMeindersma** [comment]
Nothing happened at the hackathon
