### ISSUE TITLE
Add two new sponsors

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#231]
We have two new sponsors!!! And we want to add them on our site. 

One is Jobber and one is Dotdash Meredith. (probably use the middle logo for jobber)

These should come first!  Cause they have given us a lot of money. And maybe they should be bigger too? or have their own line? idk something to stand out

The copy for Jobber will be: Thanks to Jobber for allowing us to have a space for meet ups for the next year! Couldn't happen without them!
The copy for Dotdash Meredith will be: Thanks to Dotdash Meredith for providing us with pizza and swag to help our meetups off the ground. 

![Dotdash_Meredith svg (1)](https://github.com/devedmonton/DES-Website/assets/17459171/833c480e-bd2e-47c4-a41d-3eb40acfcdf5)
![Jobber-Powered_By_Jobber-July2023-Badge_Green](https://github.com/devedmonton/DES-Website/assets/17459171/b4c10ba4-de25-49b9-8c98-851f942c896b)
![Jobber-Powered_By_Jobber-July2023-Text_Navy](https://github.com/devedmonton/DES-Website/assets/17459171/ce2325e3-bd6a-48d1-ae74-6dcc34d8d39e)
![Jobber-Powered_By_Jobber-July2023-Badge_Navy](https://github.com/devedmonton/DES-Website/assets/17459171/d4614932-797d-4b1e-95fd-27b74b2d331d)

**Comment by henrque** [comment]
Hey, maybe something like that
![image](https://github.com/devedmonton/DES-Website/assets/43590514/9a84cdde-7186-418b-a6a5-81386ad7f726)

What do you think?

**Comment by MandyMeindersma** [comment]
I absolutely love that. 

There is one thing though 😅  literally last night we got a third sponsor. 

So dotdash meredith and jobber gave us a lot of money, they are like gold tier

and then the new sponsor (Place) is like a silver sponsor

and then the only sponsors are much less than that 


So now I am not sure how to display that 😅 

I guess we could just have a h3 or something.

instead of gold, silver and basic though I would want it to say like terrabyte, bye and bit level hahaha

**Comment by MandyMeindersma** [comment]
![Powered PLACE logo TM (1)](https://github.com/devedmonton/DES-Website/assets/17459171/dfd5a7de-6674-4647-91ff-81ac42f4cc9e)
![Powered PLACE logo TM](https://github.com/devedmonton/DES-Website/assets/17459171/82699861-85f9-4e3a-a130-7bd4a682cab0)

The copy for Place will be: Thanks to Place for providing us with funding for events and providing job shadow opportunities to our hackathon winners.

**Comment by henrque** [comment]
like this?
![image](https://github.com/devedmonton/DES-Website/assets/43590514/8e53dbe9-8975-45da-ace1-a66aa229defc)

Or changing terabyte tier like before?

**Comment by MandyMeindersma** [comment]
Oh yeah I think I like that. Do you mind making a pr with that?

Cause our build will create a version where I can go test it on different widths (like mobile, desktop etc)

Cause I just want to make sure it looks great from all widths
