### ISSUE TITLE
Pull 3 latest YouTube videos from our channel and display thumbnails/descriptions on homepage

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/DES-Website#24]
This is a stretch goal, but it would be nice to drive traffic to our YouTube channel by pulling the three latest YouTube videos during the Nuxt.js build and making them display on the home page.

**Comment by MarkBennett** [comment]
I'm not super familiar with Nuxt.js. Any idea how to do this @stormwarning or @dboydgit?

**Comment by stormwarning** [comment]
I haven't looked at the YouTube API in a while, but it should be possible to call the API at build time  and grab that data to display somewhere.

**Comment by dboydgit** [comment]
We could set up a cloud function that pings the youtube API and returns the latest videos? Might not be building the site that often when it's more established.

**Comment by dboydgit** [comment]
@MarkBennett does DES have a google account that I could use to setup a youtube api key?

**Comment by MarkBennett** [comment]
> @MarkBennett does DES have a google account that I could use to setup a youtube api key?

If I add you to the YouTube brand account can you get it from that?

**Comment by dboydgit** [comment]
> > @MarkBennett does DES have a google account that I could use to setup a youtube api key?
> 
> @dboydgit If I add you to the YouTube brand account can you get it from that?

I'm not sure, the API keys are managed through the google dev console, not through youtube

**Comment by MarkBennett** [comment]
> I'm not sure, the API keys are managed through the google dev console, not through youtube

Ok. Let's check it out in the AM @dboydgit!

**Comment by DerrykBoyd** [comment]
Do we still want to do this? It's been a few years 😅

**Comment by MandyMeindersma** [comment]
hahaha and all our youtube videos are quite old :P closing
