### ISSUE TITLE
Add title to all pages 

### ISSUE THREAD

**Issue by henrque** [devedmonton/DES-Website#240]
At the moment, none of the pages in the project have a header or a title, which causes the URL to be displayed in the browser instead of a title. I want to add a title to all the pages so that it will appear like the image below.

![Captura de tela de 2023-10-03 14-27-05](https://github.com/devedmonton/DES-Website/assets/43590514/6141f628-9277-47ea-8d27-e38697e464d5)

I could work on this myself!

**Comment by MandyMeindersma** [comment]
That would be perfect if you wanted to work on it! Thank you!

Remind me to credit you in your pr (will allcontributors) for ideas too
