### ISSUE TITLE
Add WorkNicer as a resource

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#241]
Maybe put them closer to the top cause then have been supporting us a ton!

this is the blurb to add:
Work Nicer is Alberta’s number one coworking community, with six outposts across Edmonton and Calgary. Designed for teams of one to 100, Work Nicer is home to 1,400 members and 400+ businesses. From graphic designers and marketing teams, to accountants and lawyers, Work Nicer is where awesome people come together to be productive in an inspiring and supportive environment. After all, no one succeeds alone!

This is the photo they would like added but I have to add it to image kit 
![Work Nicer High Res Logo](https://github.com/devedmonton/DES-Website/assets/17459171/b01c2ea1-398e-48bb-bbae-4f5f4c48ee4e)

**Comment by MandyMeindersma** [comment]
this is the link to the file, you don't need the full link, you really just need the path, see other images for examples:

https://ik.imagekit.io/des/WorkNicer_9PHPpKJxJ.png?updatedAt=1696355650217

**Comment by shassshank** [comment]
Hi, I would like to do this, Please assign it to me.
