### ISSUE TITLE
figure out why we keep getting weird "mixed content" things in the build

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#244]
![image](https://github.com/devedmonton/DES-Website/assets/17459171/cb76ba4c-e56f-488a-a796-26d47a73612a)

**Comment by MandyMeindersma** [comment]
cc @DerrykBoyd https://answers.netlify.com/t/builds-stopped-reporting-mixed-content/103565

**Comment by MandyMeindersma** [comment]
hmmmm they say just remove the check...

**Comment by DerrykBoyd** [comment]
> hmmmm they say just remove the check...

OK removed, we can hopefully see it's gone on the next build.

**Comment by MandyMeindersma** [comment]
The latest pr looks good! I'll close this (maybe we have to worry about adding it back but I'll keep watching that thread you posted to see if they fixed it)
