### ISSUE TITLE
Weird css bug with newsletter sign up?

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#258]
So if I got to devedmonton.com the newsletter sign up is absolutely messed up but then if I click onto a page and click back then it is fine. Some sort of css that isn't loaded?

if I am just on home page:
![image](https://github.com/devedmonton/DES-Website/assets/17459171/f36a0955-3cfa-4918-bcad-33e9c3c92919)

After I click back:
![image](https://github.com/devedmonton/DES-Website/assets/17459171/309047ae-b9dd-4231-a4c7-66c5e1c02de4)

**Comment by DerrykBoyd** [comment]
This was introduced with some invalid `<head>` tags in the page templates causing hydration errors.

Head, Title, Meta tags should use the capitalised Vue component versions as per the Nuxt docs https://nuxt.com/docs/getting-started/seo-meta#components
