### ISSUE TITLE
When I go to the board recruiting page it is broken

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#261]
When I go to the board recruiting link it is broken: https://devedmonton.com/board_recruiting

But if I got to the board page and then click the "board recruiting page" link then it works fine

![image](https://github.com/devedmonton/DES-Website/assets/17459171/148c6322-a7e7-4b46-b50b-e2f6470a2958)

**Comment by DerrykBoyd** [comment]
Same issue as https://github.com/devedmonton/DES-Website/issues/258#issuecomment-1762664750 should be fixed with #263
