### ISSUE TITLE
`npm run pr-checks` should be run when I push a commit

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#265]
make some sort of git hook

**Comment by DerrykBoyd** [comment]
@MandyMeindersma can you assign this to me, I'd like to explore setting this up at a github action

**Comment by DerrykBoyd** [comment]
Actually no need to github actions, I realised we were already checking the linting and tests on netlify as part of the build process, so I can add the formatter there as well easily. #266 does that

**Comment by DerrykBoyd** [comment]
Sorry for hijacking 😅 just noticed the simple fix so wend ahead.

**Comment by MandyMeindersma** [comment]
oh but I was thinking it's probably helpful to do it as a pre push git hook. I still might do that? keeps the pr's cleaner?

**Comment by DerrykBoyd** [comment]
> oh but I was thinking it's probably helpful to do it as a pre push git hook. I still might do that? keeps the pr's cleaner?

Yeah that's an option. I'd be a little concerned about first time contributors not knowing how the git hooks / formatter works and not being able to get support. With an open PR it would be easier for someone to coach them through that 

I would probably also only run the format check on pre push, I think it's a valid workflow to push up some code with lint / test errors with the intention of collaborating or coming back to fix.

**Comment by MandyMeindersma** [comment]
Maybe add a note in the readme or contributing guidelines about --no-verify?

Would that be a happy compromise? hahah

**Comment by DerrykBoyd** [comment]
Yup for sure. 😀

**Comment by MandyMeindersma** [comment]
ah okay based on the last pr I helped with, you're right. Having them done in the pr is better
