### ISSUE TITLE
Hover state for button is not ideal

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#275]
It just disappears on hover state

![image](https://github.com/devedmonton/DES-Website/assets/17459171/7015527e-5fb0-4ec6-91e2-e00687366788)

and then on hover:

![image](https://github.com/devedmonton/DES-Website/assets/17459171/fe065bac-4d80-4293-9bd0-db04fdcec264)

**Comment by MXMxRazer** [comment]
```Vue 
<VButton appearance="inverted">About Our Slack</VButton
```

line 51 - 52 in ```index.vue```. See there's an appearance attribute set to "inverted". 

That VButton is a custom component in Vue. If you follow the file inside the component folder.


``` Vue
<button
            type="button"
            class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white border-brand-primary focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-150"
            :class="[
                appearance === 'default'
                    ? 'text-brand-primary hover:text-white bg-white hover:bg-brand-primary hover:text-white'
                    : null,
                appearance === 'inverted'
                    ? 'text-white hover:text-brand-primary bg-brand-primary hover:bg-white'
                    : null,
            ]"
>
``` 

You can see that the button tag reflects your VButtton, and theirs an custom "appearance" attribute here, which can be assigned to 'default' or 'inverted'.  

``` 
Your Hovering effect was caused due to the CSS 'text-white hover:text-brand-primary bg-brand-primary hover:bg-white' 
written in the 'appearance === inverted' section.
```

So, Just change the tailwind inside the ternary operator, or change the entire appearance section to modify it according to your needs.

**Comment by LalitDeore** [comment]
Hey @MandyMeindersma  i can work on this issue could you please assign this task to me so i can work on this issue?

**Comment by LalitDeore** [comment]
Hey @MandyMeindersma I am not familiar with Vue. Could please tell me in which file is the all tailwind css of about our slack button i found this button
`<a href="#about-our-slack">
                            <VButton appearance="inverted"
                                >About Our Slack</VButton
                            >
                        </a>`
                        here i can not see any tailwind css. so not able where to updated the css.

**Comment by MandyMeindersma** [comment]
Hey @LalitDeore so the beauty of tailwind is that their is no css. You add classes onto the HTML tags and they write the css for you

So lets take margin for example:
https://tailwindcss.com/docs/margin#add-margin-to-a-single-side

I can add `class="mt-6"` which will add margin to the top of whatever HTML tag I am adding it too. 

Let me know if that helps or if you need another hint to get started :)

**Comment by SeaBebop** [comment]
Made an attempt on this in https://github.com/devedmonton/DES-Website/pull/279

**Comment by MandyMeindersma** [comment]
@SeaBebop You have the correct approach but this issue is assigned to @LalitDeore and as they are in the middle of making changes to their pr and I would like to give them a chance to learn. We have many other issues that are open :)

I'll close your pr for now and reopen after @LalitDeore has had a chance
