### ISSUE TITLE
There are a couple meetups that do not exist on the DES site but they are active, we have to find contacts and photos and get them on the site to highlight them!

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#300]
Meetups we don't have on the DES site
- CMX Edmonton Chapter
- ~NeurAlbertaTech~ (added)
- Edmonton Computer Club
- Edmonton Gen AI Meetup Group

Ideally for each we would get:
- logo
- link where people can learn more (doesn't have to be a website, can be a meetup group or a social media link)
- little blurb about them
- maybe a contact email of a couple of the organzers to be used for internal DES things (like if we have space they can use or if they need a bank account or anything)

**Comment by phageogram** [comment]
I can reach out to NeurAlbertaTech and ask for preferred contacts and photos as I know someone from that organization!

**Comment by phageogram** [comment]
Done :) Just wanted to let you know that I've connected with them and things are in the works. They said they'd like to be featured on the site. I asked them to send a blurb and an image file of their logo, so just waiting on that for now.
