### ISSUE TITLE
migrate website content to `@nuxt/content`

### ISSUE THREAD

**Issue by arashsheyda** [devedmonton/DES-Website#311]
right now the content of website is coded in the pages (getting data from store), I suggest that we use [@nuxt/content](https://github.com/nuxt/content), this will add support for MarkDown which will be more convenient to use and manage.

I would be happy to work on this if approved.

**Comment by MandyMeindersma** [comment]
ooooh! So I don't actually have that much nuxt experience :P I am a Java dev by day. So I will defer to your expertise.

Tagging a couple other in case they have opinions @dcampbelld  @deejayjay  @DerrykBoyd 

If there is no reply in a couple days i say go for it!

**Comment by DerrykBoyd** [comment]
> ooooh! So I don't actually have that much nuxt experience :P I am a Java dev by day. So I will defer to your expertise.
> 
> Tagging a couple other in case they have opinions @dcampbelld  @deejayjay  @DerrykBoyd 
> 
> If there is no reply in a couple days i say go for it! 

Sound good to me 🙂

**Comment by deejayjay** [comment]
@arashsheyda: Is there any advantage to using `@nuxt/content` over adding these contents directly in the pages? 
I haven't played around with `@nuxt/content` at all, so I am not sure about the impact of this change on the existing style.

**PS:** I don't particularly like having the content inside the `Pinia` store either because it is static content.

**Comment by arashsheyda** [comment]
@deejayjay I think the benifts of it would be:

- **Easy Content Management:** `@nuxt/content` lets us write content in Markdown, a format that's simpler and more organized than directly coding it in pages. This means it's easier to edit and maintain content.
- **Separation of Content and Code:** With `@nuxt/content`, we can keep content separate from the code, making it clearer and more manageable.
- Automatic Page Generation: @nuxt/content can automatically create pages based on our Markdown files, saving us time and effort in creating and updating pages manually.
- also during this process, we get some kinda re-do of website (I noticed we're using some modules for nxut 2, option api and e.g.)

As for the impact on our existing style, `@nuxt/content` doesn't add any style to the project, but we have to add some css for markdwon tags (e.g. headings, p, a fontSize & color...) and as long as we use the same values as used before I don't think it would be a problem.

a preview of how it'll look:

<img width="1728" alt="Screenshot 2024-03-15 at 9 01 51 AM" src="https://github.com/devedmonton/DES-Website/assets/38922203/4b519cee-ada9-4ced-9ce8-2f488b34bdee">

<img width="1728" alt="Screenshot 2024-03-15 at 9 12 39 AM" src="https://github.com/devedmonton/DES-Website/assets/38922203/8bfb383d-3f28-448e-9d85-b98ef3a93473">

**Comment by deejayjay** [comment]
@arashsheyda: In that case, I like this. This makes the content more manageable for sure. 
Two more questions: 
- What if want to add an HTML element that is not supported by MarkDown?
- Will this change affect the sites SEO adversely?

**Comment by arashsheyda** [comment]
> * What if want to add an HTML element that is not supported by MarkDown?

@deejayjay do you mean like if you wanted to use HTML code outside of MD format? we can use any HTML tag and vue components, an example would be:

<img width="1237" alt="Screenshot 2024-03-15 at 4 02 38 PM" src="https://github.com/devedmonton/DES-Website/assets/38922203/412a47dd-412f-4a78-92ff-7499e0385b18">

> you can find more info on https://content.nuxt.com/usage/markdown

<br><br>

> * Will this change affect the sites SEO adversely?

no `@nuxt/content` is super SEO friendly. as a matter of fact there is `@nuxtjs/seo` module which helps you with SEO and I did install that and it looks this:

| @nuxt/content | devedmonton |
:--------------:|:-------------:
<img width="1728" alt="Screenshot 2024-03-15 at 4 31 45 PM" src="https://github.com/devedmonton/DES-Website/assets/38922203/3ab12014-395f-428f-a2e7-6a4add9ed2b0"> | <img width="1728" alt="Screenshot 2024-03-15 at 4 32 58 PM" src="https://github.com/devedmonton/DES-Website/assets/38922203/beac5b04-6eeb-4a72-bda0-df7269d463a0">

**Comment by deejayjay** [comment]
@arashsheyda: I like how simple the content looks, but I'm a bit concerned about the learning curve, especially if someone who is not very familiar with the Vue/Nuxt environment has to work in any of the pages. What do you think @MandyMeindersma ?

**Comment by MandyMeindersma** [comment]
Wow those SEO results are impressive. 

I agree with the learning curve. Lately I have been using this repo to teach students how to contribute to open source. It gives them a relatively easy spot to learn, especially with a language and pattern they already know. But I mean if they know html, then they should know markdown...

I love this though and I want to learn more about it so maybe the students will feel the same?

@arashsheyda Do you want to push what you currently have (doesn;t need to be perfect or working - though it looks like you already have that)and then maybe I'll tag a couple students in the pr and see if they have any complaints?

I am leaning on just doing it though cause it seems very cool

**Comment by deejayjay** [comment]
I really love the idea of having students contribute. Let's do it!!!

**Comment by arashsheyda** [comment]
@MandyMeindersma it's great to hear students contributing to open source! Nuxt has so much potential & cool features.

maybe I can just list the usefull modules and ideas so others can contribute? I think that would be better 😄

**Comment by MandyMeindersma** [comment]
No it looks like the changes you have now would be a little daunting for a first time contributor :P I say push it!

If you have idea's for other easy issues though I would love to see those as issues. (Unless you want to do them too, honestly I am just happy with any contributions)

Thanks so much @arashsheyda

**Comment by arashsheyda** [comment]
@MandyMeindersma Okay then, I'll try to open a PR tomorrow.

No I would love to see others contribute to open source!
