### ISSUE TITLE
Add some padding to the "Responsibilities" title

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#320]
on the board recruiting page https://devedmonton.com/board_recruiting

we have this:
![image](https://github.com/devedmonton/DES-Website/assets/17459171/cca26ef7-1b6f-4836-a01d-87551c01e52b)

And I would love to see some more padding about the responsibilities title

**Comment by yaroslavhoretskyi** [comment]
I can take it

**Comment by MandyMeindersma** [comment]
#339
