### ISSUE TITLE
feat: text selection/highlight style

### ISSUE THREAD

**Issue by arashsheyda** [devedmonton/DES-Website#329]
update text selection/highlight style to fit our theme vibe, and it should work well in dark mode

![image](https://github.com/devedmonton/DES-Website/assets/17459171/baa68a1a-bfba-4029-9a69-30b482c6e997)

**Comment by yaroslavhoretskyi** [comment]
I want to take it

**Comment by yaroslavhoretskyi** [comment]
I fixed some with this pr: #338
