### ISSUE TITLE
Update to Node 20

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#336]

**Comment by ajyong** [comment]
I'm still piecing together our tooling, but I think the scope of work here is:

- Change `.nvmrc`
- Ensure GitHub actions stop failing just because we use an old, unsupported Node version

Is the above missing anything?

**Comment by arashsheyda** [comment]
@ajyong the `.nvmrc` is for developing locally, the workflow is already on node 20 but somehow sometimes it's doing weied things (like adding unuseful things to package.json)
