### ISSUE TITLE
Fix npm warn errors on `npm install`

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#348]
there are like 250 of them :P 

<img width="573" alt="image" src="https://github.com/devedmonton/DES-Website/assets/17459171/7a33c2d4-f06b-4e46-8f94-ce7b8087594f">

**Comment by arashsheyda** [comment]
#336 would fix this

**Comment by MandyMeindersma** [comment]
oooooh thank you @arashsheyda I'll close :)
