### ISSUE TITLE
disable scrolling when modal is open

### ISSUE THREAD

**Issue by arashsheyda** [devedmonton/DES-Website#362]
if you go to https://devedmonton.com/events and then click on an event from the calendar, a modal will open, and user can still scroll in the background while the modal is open. the expected behaviour would be to stop the scrolling when it's open

**Comment by acenasir** [comment]
I can try to take this one :)

**Comment by DerrykBoyd** [comment]
Oh darn, I didn't realise this was assigned 🤦 sorry @acenasir if you are still working on it let me know I will close my PR

**Comment by acenasir** [comment]
Tried - Failed - @DerrykBoyd please take this one @arashsheyda please assign to @DerrykBoyd
