### ISSUE TITLE
Rearrange header

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#368]
I want our list of companies (on /resources) to have their own highlighted page

- alphabetize the lists of companies
- give them their own page
- remove contacts from the header
- put companies in the place of contact
- add contact to the footer

**Comment by arashsheyda** [comment]
we could also make the `Resources` a dropdown

**Comment by Anubhav2k3** [comment]
I would like to work on this issue please assign it to me.

**Comment by MandyMeindersma** [comment]
Hey @Anubhav2k3  I already assigned you some and I would like to have some open issues for the influx of students we will have on october 1st  :)

**Comment by AACHAL2303PATIL** [comment]
I would like to work on this issue please assign it to me.

**Comment by MandyMeindersma** [comment]
Hey @AACHAL2303PATIL did you want to wait until hacktoberfest?  https://hacktoberfest.com/

You will get fun digital rewards :)

**Comment by AACHAL2303PATIL** [comment]
I would like to make my contributions to the project now, as I need to present it as part of my assignment. Thank you for your understanding.
