### ISSUE TITLE
Remove Canada Learning code from the site

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#369]
They no longer are a chapter :( CLC is closing all chapters

**Comment by Anubhav2k3** [comment]
I would like to work on this issue please assign it to me.

**Comment by Anubhav2k3** [comment]
I would like to make my contributions to the project now, as I need to present it as part of my assignment. Thank you for your understanding.

**Comment by MandyMeindersma** [comment]
Oh absolutely! Thanks so much!
