### ISSUE TITLE
Add leetcode meetup night to our list of meetups

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#371]
https://devedmonton.com/meetups

**Comment by MandyMeindersma** [comment]
blurb: 
Leetcode Night: Code, Collaborate, Conquer!
Join us for **Leetcode Night**, where coders of all levels tackle Leetcode problems together. Whether you're prepping for interviews or just want to sharpen your skills, this is the perfect chance to collaborate, share strategies, and learn new techniques. Bring your laptop, team up, and let's solve some coding challenges!
**Ready to level up?** See you at Leetcode Night!

**Comment by MandyMeindersma** [comment]
link:
https://www.meetup.com/edmontonunlimited/events/

**Comment by MandyMeindersma** [comment]
photo:
https://ik.imagekit.io/des/meetups/leetcode.png

**Comment by Anubhav2k3** [comment]
I would like to work on this issue please assign it to me.

**Comment by MandyMeindersma** [comment]
Will do @Anubhav2k3  :) 

How many do you have to do for your assignment? :) I want to make sure we still have some left for hacktoberfest :)

**Comment by MandyMeindersma** [comment]
Did you still want to work on this one @Anubhav2k3

**Comment by Anubhav2k3** [comment]
Yes, I want to work on it.
