### ISSUE TITLE
Centre Header Items

### ISSUE THREAD

**Issue by arashsheyda** [devedmonton/DES-Website#376]
right now, if you look at our header, the items are not centred. the goal is make sure that they are centred!

| Current | Goal |
:--------------:|:-------------:
<img width="1726" alt="Screenshot 2024-09-27 at 12 15 40 PM" src="https://github.com/user-attachments/assets/972922f8-2d6e-45a2-bf12-ecc7197102b5"> | <img width="1726" alt="Screenshot 2024-09-27 at 12 17 27 PM" src="https://github.com/user-attachments/assets/985e6252-b45c-4dec-bda1-9805f7e3f8ca">

**Comment by PartishtaP** [comment]
Please assign me this issue.
I would like to work on it
