### ISSUE TITLE
Add bsides to events/meetups

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#379]
Add https://www.bsidesedmonton.org/ to events and meetups.

image:
https://ik.imagekit.io/des/events/bsides.png

**Comment by blizet** [comment]
Please assign this to me

**Comment by blizet** [comment]
I've already made my contribution for Hacktoberfest, which starts on Monday.

**Comment by MandyMeindersma** [comment]
PRs do not count for hacktoberfest until after october 1st

**Comment by MandyMeindersma** [comment]
<img width="893" alt="image" src="https://github.com/user-attachments/assets/b3f41efd-8165-428b-bfd6-b4a2718cdab3">
