### ISSUE TITLE
Remove Intuit from list of Edmonton companies

### ISSUE THREAD

**Issue by jasminewoo** [devedmonton/DES-Website#387]
Intuit is no longer operating out of Edmonton. Let's remove them from the list of local companies.

Screenshot showing where this needs to be removed:
![remove-here](https://github.com/user-attachments/assets/76cbb7ce-0f4e-4c94-bb09-03f0617a09f8)

**Comment by acenasir** [comment]
I can take this

**Comment by jasminewoo** [comment]
Just assigned this to you, @acenasir
