### ISSUE TITLE
List other groups

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#393]
We would want another section for this. Maybe it could go on the meetups page? below all the other meetups

We could just show logos of like slack and facebook as the images. 
https://ik.imagekit.io/des/meetups/discord.png
https://ik.imagekit.io/des/meetups/facebook.png
https://ik.imagekit.io/des/meetups/slack.png

Slack groups:
- Product Edmonton - http://productedmonton.slack.com/
- Edmonton Start Up community- https://yegstartup.slack.com/join/shared_invite/zt-czl41ymv-IlCrO1Na2KwqV9pb37v4kQ#/shared-invite/email
- Digital Edmonton (UX/IA) - https://join.slack.com/t/digitaledmonton/shared_invite/zt-7ka8gm45-cVNFyy1wp9R0wunz46vrlQ
- YEG DEV - https://yegdev.slack.com/
- Google Developer Group - http://gdg-cloud-edmonton.slack.com/ 

Discord Groups:
- Edmonton Data science - https://discord.gg/uVuTx8G3
- Alberta programmers - https://discord.gg/XEjjP7KY
- Alberta Game Developers - https://discord.gg/7ZqjBCH4
- Junior Developers - https://discord.gg/qK9ydrA2SC

Facebook groups:
- UX Edmonton - https://www.facebook.com/groups/59071219138
- YEG Women in Tech - https://www.facebook.com/groups/YEGWomenInTech

**Comment by dgmouris** [comment]
> We would want another section for this. Maybe it could go on the meetups page? below all the other meetups

I'm pro putting this on the meetups page @MandyMeindersma

**Comment by Atremblay9** [comment]
Hey! 

Working on this and noticed that the Startup Edmonton's Facebook page description is "We've evolved & moved! Startup Edmonton is now a program of Edmonton Unlimited - Edmonton's innovation-focused authority. Don't worry; you can still take advantage of Startup Edmonton's renowned programming there too!" . 

I'm not sure if this means that the company is now Edmonton Unlimited, but I think that this slack might have changed.

Should I be looking for the Edmonton startup Slack?  

Thanks!

**Comment by MandyMeindersma** [comment]
@Atremblay9 good digging

yeah startup edmonton is defunct but they still have a thriving slack so would love to list it

**Comment by MandyMeindersma** [comment]
I renamed it to "Edmonton Start Up Community" to be more helpful

**Comment by Atremblay9** [comment]
Hey Mandy! 
Since there isn't a provided description from the Edmonton Startup Community, I put this down as I probably shouldn't be writing anything they haven't: 
" Startup Edmonton began in 2009 as an entrepreneur-led nonprofit working to grow Edmonton’s emerging creative and tech economy through events connecting the next-generation of entrepreneurs, investors, developers and creatives.",

I am also having trouble finding the Digital Edmonton website or socials, Do you know if this group is connected to the slack? 

https://www.facebook.com/groups/uxyeg/

Thanks, I appreciate the help!

**Comment by MandyMeindersma** [comment]
@Atremblay9 Thank you for all the research you have done!

I should have been more clear in this ticket. I think a lot of these groups won't have websites or descriptions. I think just listing their name in a card would suffice for this ticket. I think our cards on the site allow for blank descriptions (I could be lying though, hopefully I am not hahah)

**Comment by MandyMeindersma** [comment]
@j-soule Thank you so much for suggesting. We are usually pretty open with tech groups but moveEd we would like to keep off the site. Thank you for asking!

**Comment by dgmouris** [comment]
Thanks for the work on thie @MandyMeindersma @Atremblay9 and @j-soule :)

**Comment by dgmouris** [comment]
This seems complete so I'm going to close this issue. We can reopen this later if there are more groups to be added.
