### ISSUE TITLE
Update leetcode night 

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#396]
**They have a new site:** http://www.leetnight.com/
**new title:** LeetNight: Code, Collaborate, Conquer!
**new blurb:** LeetNight is a free, welcoming meetup designed for coders eager to enhance their problem-solving skills. Whether you’re gearing up for technical interviews or just enjoy tackling algorithm challenges, this event offers a collaborative environment to learn and grow. It’s also a fantastic way to connect with fellow developers, share insights, and build skills together. Ready to level up? See you at Leetcode Night!

**Comment by LUCKYINGGG** [comment]
Hi Mandy, I noticed this issue and went ahead and fixed it. This is my first PR, so if I did not do it correctly, please let me know. 

PS: I am one of Dan's students.
