### ISSUE TITLE
NPM dependency warnings

### ISSUE THREAD

**Issue by DerrykBoyd** [devedmonton/DES-Website#404]
First time running the project in a while as been busy with family 😄 

When getting setup again, I can see a lot of warnings on the `npm install` step around:

- dependency conflicts
- unsupported node engine
- security warnings

Would be prudent to clean these up and possibly, once it's clean add a PR check to make sure new PR's don't introduce any new warnings.

**Comment by arashsheyda** [comment]
I could fix the issues if you'd like (I assumed other contributors will take it but it's been a while...)

**Comment by DerrykBoyd** [comment]
> I could fix the issues if you'd like (I assumed other contributors will take it but it's been a while...)

That would be awesome, thanks!
