### ISSUE TITLE
add [lang] attribute to html element

### ISSUE THREAD

**Issue by arashsheyda** [devedmonton/DES-Website#417]
this is an a11y issue, we need to add [lang] attribute to html element.

**Comment by tylersocholotuik** [comment]
Hello, I believe I have fixed this issue, but I get this error when running es lint:

```
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.6.0

YOUR TYPESCRIPT VERSION: 5.6.3

Please only submit bug reports when using the officially supported version.
```
All of the other tests pass, however.

Here is a screenshot showing the html element

![html-lang](https://github.com/user-attachments/assets/d8d77031-a6ae-416b-9713-0dadc191171d)

Please let me know if I can submit a PR, or if you would like me to solve the issue with es lint first. This is my first issue, so I want to make sure everything is good before submitting. Thanks in advance.

**Comment by arashsheyda** [comment]
hey @tylersocholotuik , yeah don't worry about that you can submit a PR 😃 thanks!

**Comment by tylersocholotuik** [comment]
> hey @tylersocholotuik , yeah don't worry about that you can submit a PR 😃 thanks!

Submitted, thank you!
