### ISSUE TITLE
Change calendar week start day from Monday to Sunday

### ISSUE THREAD

**Issue by keifererikson** [devedmonton/DES-Website#421]
There was a known bug in vue-cal that would cause the events to show on the wrong days when using the `start-week-on-sunday` prop.

This fix has finally been merged a few weeks ago! https://github.com/antoniandre/vue-cal-v4/pull/528

I can submit a PR for this issue enable that feature to greatly improve the readability of the calendar. If this is an unwanted feature I would love to hear opinions on it!

![image](https://github.com/user-attachments/assets/838f767b-6797-44d1-91a3-29625a7dd930)

**Comment by dgmouris** [comment]
Thank you I've screwed this up a few times @keifererikson

**Comment by dgmouris** [comment]
The pr looked great and I merged it thanks @keifererikson woot woot!
