### ISSUE TITLE
Images not aligned and Description a little odd.

### ISSUE THREAD

**Issue by dgmouris** [devedmonton/DES-Website#440]
As discussed in the pull request #393

And see in the image below
![image](https://github.com/user-attachments/assets/6fbcc790-c493-4a31-86e8-4286fa706c87)

In pink here description is a little large and maybe we could shorten that up.

Image in green is not alight so maybe we could do something about this. 

I don't know this would be an image kit thing or a nuxt thing but I thought that I would make this issue.

@Atremblay9 thanks for the catch hopefully we can fix this.

**Comment by arashsheyda** [comment]
@dgmouris I agree! the problem with aligning images is that the [slack](https://ik.imagekit.io/des/meetups/slack.png) image is cutted to edge and the [discord](https://ik.imagekit.io/des/meetups/discord.png) one has some space.
one thing that we can do is use the logos from `@nuxt/icon` (we have to tweak the `Horizontal` component a but to accept icons)

**Comment by MandyMeindersma** [comment]
I think I fixed the cropping on the discord icon :)

**Comment by MandyMeindersma** [comment]
<img width="388" alt="image" src="https://github.com/user-attachments/assets/99357dfd-fdbd-4d86-92d5-78dd2274ecb9">


Looks better right?

**Comment by dgmouris** [comment]
Looks great @MandyMeindersma thanks a bunch:)
