### ISSUE TITLE
Add Flutter Edmonton as a meetup!

### ISSUE THREAD

**Issue by MandyMeindersma** [devedmonton/DES-Website#448]
Title: Flutter Edmonton

Description: Welcome to Flutter Edmonton! This group is dedicated to all things Flutter, a popular open-source UI software development kit created by Google. Whether you are a seasoned developer or just getting started, this group is the perfect place to share ideas, collaborate on projects, and learn from other enthusiasts. Join us for meetups, workshops, and networking events where we discuss the latest trends, best practices, and innovative uses of Flutter. Let's build beautiful apps together!

Link: https://www.meetup.com/flutter-edmonton/

image: https://ik.imagekit.io/des/meetups/flutter.png

**Comment by leslietech** [comment]
Sorry, I picked this up in error. There is already a PR for this, and I am also seeing @tdenis29's comment above.

**Comment by dgmouris** [comment]
Closing this as this is resolved.
