### ISSUE TITLE
Meetup Card Randomization Missing/Disabled

### ISSUE THREAD

**Issue by leslietech** [devedmonton/DES-Website#453]
Hello Folks. In issue #299, the randomization of cards on the https://devedmonton.com/meetups page was implemented. I checked again, and that feature seems to be gone.

**Comment by arashsheyda** [comment]
hi there! Thanks for pointing this out.

The randomization feature is implemented on the homepage, where we highlight a selection of meetups. However, on the `/meetups` page, since all the meetups are displayed, randomization is not applied to ensure consistency and ease of navigation.

**Comment by dgmouris** [comment]
I know this might be unrelated to randomization but maybe we could put a random "featured" meetup on the home page as a replacement?

This is a passing thought and can be completely disregarded if there's no interest :)

**Comment by dgmouris** [comment]
I'm just looking at this with some folks at our open source club.

@leslietech the meetups on the home page and the resources on the home page randomize so I think either we can close this issue or perhaps change it to a single "featured meetup here" 

Maybe something like this?

![image](https://github.com/user-attachments/assets/d8078f62-e974-4f29-97ad-62711483a214)

**Comment by MandyMeindersma** [comment]
I am nervous to put anything before the slack though (cause I do think most people are using our website just to get the slack link)

**Comment by leslietech** [comment]
Thanks @arashsheyda. I tend to refer folks to the https://devedmonton.com/meetups page. So that is where I expected t see the randomization. I see than randomization is in the homepage meetups/groups component.

Regarding @dgmouris's comment about adding a random meetup in the homepage, I'll concur with @MandyMeindersma to not add it. With that in mind, we can close this issue since randomization already exists on the homepage.
