### ISSUE TITLE
Add an event calendar with upcoming DES events to the website

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/DES-Website#69]
We'll need to figure out a way to pull current events from places like meetup.com, Google Calendar, eventbrite, etc. but it would be great if we could make upcoming events more visible!

**Comment by MandyMeindersma** [comment]
this might be an old calendar with only events from meet up on it:

You might have to change the user number. https://calendar.google.com/calendar/u/0?cid=dnVuanUyNWlwYWZiczkxcW1xdjZudGhtZWdAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

@benzittlau manages it

**Comment by MandyMeindersma** [comment]
I am going to close this issue for now because this is a really big ask (with not fleshed out requirements - like where we get the events from) and none of the maintainers really have time to look over such a big ask
