### ISSUE TITLE
Add community events

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/DES-Website#75]
We need to start surfacing useful resources on the website. Here are some for students that we should be sharing:

* amii tech aid - Student Developer Conference (DevCon) - https://www.amiitechaid.com/
* HackED hackathon - https://hacked.compeclub.com/ 
* ~PolyGlot~ (not a thing any more)

**Comment by djphan** [comment]
I can take this on... for my final hacktoberfest lol
