### ISSUE TITLE
Add an "Edit This Page" on GitHub link

### ISSUE THREAD

**Issue by MarkBennett** [devedmonton/DES-Website#82]
# Acceptance Criteria
1. Display a link at the bottom of each page to make editing and fixing errors easier
2. The link should take people to the GitHub repo

# Bonus Points
1. Link directly to the page you're editing on GitHub so that people don't need to search the repo

**Comment by dboydgit** [comment]
A few things to consider with this one:

- I think only users with permissions on the repo will be able to edit files
- It will be difficult to check the linting and formatting when editing through the github UI, which will likely lead to failed builds

**Comment by MandyMeindersma** [comment]
I am going to close this because of derryks comments
